secrets:
  jalsoochak:
    username: ""
    password: ""
    database: ""
    host: ""
    port: ""
    db-url: ""

  kafka:
    clusterID: ""
  keycloak:
    adminPassword: ""
    managementPassword: ""