secrets:
  jalsoochak:
    username: ""
    password: ""
    database: ""
    host: ""
    port: ""
    db-url: ""

  kafka:
    clusterID: ""
  keycloak:
    adminPassword: ""
    managementPassword: ""
  minio:
    accessKey: ""
    secretKey: ""
    endpoint: ""
    bucket: ""
  glific:
    username: ""
    password: ""
    welcome-template-id: ""