# Default values for egov-finance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common Labels
labels:
  app: "redis"

# Container Configs
image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/redis"
  pullPolicy: IfNotPresent
  tag: "7.2.4"
replicas: "1"
httpPort: 6379