name: Image Build & SonarQube Scan for Service Discovery

on:
  push:
    branches: ["main"]
    paths:
      - 'servicediscovery/**'
  pull_request:
    types: [opened, synchronize, reopened]
    # paths:
    #   - 'servicediscovery/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  sonarqube:
    name: SonarQube scan & push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Set up JDK 21  
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run:  mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar -Dsonar.projectKey=servicediscovery -Dsonar.organization=arghyam -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        working-directory: servicediscovery
        
      - name: Configure AWS credentials
        # if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        # if: github.ref == 'refs/heads/main'
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker build
        # if: github.ref == 'refs/heads/main'
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg WORK_DIR="servicediscovery" -t $ECR_REGISTRY/servicediscovery:$IMAGE_TAG -f build/maven/Dockerfile .
          docker push $ECR_REGISTRY/servicediscovery:$IMAGE_TAG



